### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by harrysouthworth** [epam/parso#2]
Hello.

Thanks for all your efforts with Parso and for making it open source.

I've been struggling to find jars for all the dependencies. I eventually got the correct version of opencsv, but am still struggling to get the correct version of FEST Assertions.

Please let me have a link to the correct version. I also suggest that you add links to the README

Again, many thanks,
Harry

**Comment by printsev** [comment]
Hi Harry,

You can use maven search functionality to locate certain artifacts:
http://search.maven.org/#search%7Cga%7C1%7Cfest

If you have a maven project, it would download all the required dependencies automatically. Also I don't think any of these dependencies are required to use parso in some application so that's why ideally we don't want to add them to README.

Hope that answers your question.

**Comment by harrysouthworth** [comment]
Thanks for your help. I'm a Java n00b or would have known that. I've now got Parso buiding correctly and my wrapper code appears to work. I'll let you know if previous errors I had still exist.

Thanks again,
Harry

**Comment by printsev** [comment]
Great to hear that Harry.

Please feel free to reach out if you need any help.

Igor
