### ISSUE TITLE
Unable to read sas7bdat columns

### ISSUE THREAD

**Issue by drivasudc** [epam/parso#43]
Hi guys,

I have a lot of .sas7bdat files generated from different systems and time that I am able to read with this library, but when I try to read the new ones generated a couple of days ago, the library is unable to find any colums and it does not return any result.

Is this some kind of bug that you are not aware of? how can I fix it?

I will attach a sample file so you can also test it.

[sas_sample.zip](https://github.com/epam/parso/files/3037909/sas_sample.zip)

Thanks a lot, great work here!

**Comment by Yana-Guseva** [comment]
Hi @drivasudc,

Many thanks for the sample file. Is this a file that you simply generated on some SAS platform, or did you first generate a file and then delete a few rows from it? I am asking because we have a similar problem with files from which some lines have been deleted [().](https://github.com/epam/parso/issues/38). The problem is Parso does not know all the possible types of pages that can be used in SAS, so Parso cannot handle certain types of pages, for example, a page with a type of '640', which is used in your test file. Currently fix for your problem is available in the 'issue_38/deleted_records' brunch but it does not merged into master.

**Comment by drivasudc** [comment]
It was directly generated on a SAS platform and the new branch worked just perfect!! 

Thank you very much @Yana-Guseva :)
