### ISSUE TITLE
Endless loop in constructor with empty ByteArrayInputStream

### ISSUE THREAD

**Issue by mikrovvelle** [epam/parso#56]
The following code, using the `SasFileReaderImpl` class, will lead to an endless loop:

```java
  byte[] emptyArray = new byte[0];
  ByteArrayInputStream emptyStream = new ByteArrayInputStream(emptyArray);
  SasFileReaderImpl emptyByteArrayStreamReader = new SasFileReaderImpl(emptyStream);
```

Probably no one should be passing in empty ByteArrayInputStreams to the constructor, but instead of getting caught in an endless loop, it would be helpful to throw an exception instead. This would allow classes extending `SasFileReaderImpl` to easily catch this kind of bad input.

---

The loop takes place in `getBytesFromFile` in `SasFileParser`, line 750:

```java
  while (actuallySkipped < offset[i] - currentFilePosition) {
    try {
      actuallySkipped += sasFileStream.skip(offset[i] - currentFilePosition - actuallySkipped);
    } catch (IOException e) {
      // never reach this far
```

`actuallySkipped` and `currentFilePosition` are stuck at 0, while `offset[0]` is 32, so the `while` statement never exits.

**Comment by syjer** [comment]
Hi, I was kinda reluctant to open the issue here, as it has an impact on the Apache Tika project and I was trying to figure out who to contact and how. 

You can do a Denial of Service with a correctly crafted input, so this issue is quite important.

See the gists: https://gist.github.com/syjer/9ffebab4538fbc4242d10e50fa5a4454

**Comment by printsev** [comment]
closed thanks to xantorohara
